### ISSUE TITLE
Cursor moves to the top left corner on macOS

### ISSUE THREAD

**Issue by dnicolson** [iortcw/iortcw#106]
When moving the cursor towards the middle of the window, it jumps back to the top left corner. It's possible to move the cursor closer to the bottom right area but it's very rare and snaps back to the top left when the cursor moves again

![iortcw (1)](https://user-images.githubusercontent.com/2276355/97488324-61997800-195e-11eb-99e0-a34d71b0f75c.gif)

iortcw 1.51c.
macOS 10.14.6 and macOS Big Sur beta (20A5395g).

**Comment by MAN-AT-ARMS** [comment]
Possibly an issue with this SDL version. I will be upgrading that to newest version soon. I have no way of testing on that version of MacOS because my hardware doesn't support running it.

**Comment by dnicolson** [comment]
It might be an SDL issue in general, as basically the same issue occurs in the RTCW-iOS project on tvOS after the [Upgraded to use SDL instead of GLKit](https://github.com/tomkidd/RTCW-iOS/commit/11d210f491b2b52674a3fdd316860546ee0f63c3) commit.

It doesn't seem like it's version-specific as macOS 10.14, 10.15 and 11.0 are affected.

**Comment by tomkidd** [comment]
I haven't tried to build this in a while for macOS (though I'll try again soon having seen this). 

That said, I saw something similar in Quake 3 when I was experimenting with using a version of the QVMs that supported absolute positioning. On a touchscreen you're going to just want to tap the screen but the code is contingent on relative mouse movements. Worked fine on the touchscreen but without additional consideration it would produce a similar effect since the code is interpreting the absolute coordinates of the touches as relative mouse movements.

I have no idea if that's related to this at all, but I thought I'd toss that out there.

**Comment by tomkidd** [comment]
OK so yeah I think that's what you're encountering. 

The .qvm files I created for use with the iOS project have the additional logic to handle the absolute positioning needed with a touch screen

https://github.com/tomkidd/RTCW-iOS/blob/master/RTCW-SP/qcommon/common.c#L1807

The problem is if you leave them in the "vm" directory under "Main" and then reference that directory with the regular desktop iortcw client, then it picks up those qvm files and it screws up the mouse cursor. It's interpreting the small movements of the mouse as absolute coordinates which is why it stays up in the corner. 

And part of the reason I know this is it bit me just now in fooling around with ioq3 because I had done the same thing only with Quake 3. It's easy to lose track of what is where.

There's probably a good way for both of these methods to coexist but I haven't figured it out yet. 

Try removing the "vm" directory from your Main directory and try again. The good news is that if that works it's not an SDL or code issue.

**Comment by dnicolson** [comment]
That's the issue, I should've been more careful copying the Main directory.

**Comment by MAN-AT-ARMS** [comment]
If you don't want to use .qvm files use the cvars:

vm_cgame 0
vm_game 0
vm_ui 0

With these set to 0 it will use the .dylib files (shared libraries) instead. The default value of 2 will use .qvm files.

So both can coexist in the same folder
