### ISSUE TITLE
Port to Apple Silicon

### ISSUE THREAD

**Issue by polanfong** [iortcw/iortcw#111]
This may be along shot, but any chance this could be ported to M1 Mac? Just getting ideas how feasible this is and if it needs to be forked separately.

**Comment by MAN-AT-ARMS** [comment]
It's certainly possible that it will build but I don't have the hardware to test. For sure, it will need to be built with libraries and frameworks that Apple includes (since the prebuilt libraries in the repo are PPC/Intel builds - i.e. OpenAL, SDL2).
I'm not sure of the status of SDL builds on that arch.

I'm sure the dedicated server for MP will probably build unaltered.

**Comment by tomkidd** [comment]
SDL builds for Apple Silicon as of 2.0.12. I figured this out when I recently shipped a little freeware game as a Universal purchase/app

https://github.com/tomkidd/disasteroids3d (has source, link to App Store, article with details, etc.)

That said I'm just assuming it really works because I haven't tried it on a Silicon-based Mac myself. But it built and Apple accepted it. 

Not sure about OpenAL but being open source there's a good chance someone has done or will do the work.

And seeing as how I got this port working on iOS and that's ARM, etc., I'm sure it could work.

**Comment by MAN-AT-ARMS** [comment]
OpenAL soft is usually a bit of a pain building for Mac in general. Apple does usually have the old Creative version as part of it's libraries and frameworks, not sure if they still do or not. They change their development environment so often that projects often get broken (including SDL).
