### ISSUE TITLE
Flatpak command works from terminal but not Steam Launch options

### ISSUE THREAD

**Issue by HellsBells24** [iortcw/iortcw#117]
Running into a confusing issue here as I attempt to run the iortcw Flatpak. I've successfully installed it and copied my original game files, Venom mod files, and NVIDIA shaders to the correct directory. The game runs without issue, provided I run from the terminal or the Pop OS activities screen itself.
Generally speaking what I do with my Steam games that are run via flatpak based source ports (GZDOOM and Yamagi Quake 2) is to place the launch command in the launch options of Steam (yes I know I can simply add as a non Steam game, this feels more elegant to me). In this case, that command is "flatpak run com.github.iortcw.iortcw %command%"
For some reason, despite the fact that the game runs fine without Steam, launching via Steam with this launch option returns

"pak0.pk3" is missing. Please copy it
from your legitimate RTCW CDROM.

Also check that your iortcw executable is in
the correct place and that every file
in the "main" directory is present and readable.

. See "/home/chas/.var/app/com.github.iortcw.iortcw /mnt/6173eb9c-38d6-4b95-b26d-6d873df543c0/SteamLibrary/steamapps/common/SteamLinuxRuntime_soldier/_v2-entry-point --deploy=soldier --suite=soldier --verb=waitforexitandrun -- /mnt/6173eb9c-38d6-4b95-b26d-6d873d" for details.

Despite all the necessary files being in place in the flatpak directory.

Here's a gist of the referenced file, I'm not sure what can be gained from it or what it's saying, however.
https://gist.github.com/HellsBells24/d26915aaf858c7da57f6974ce007a35e

**Comment by smcv** [comment]
> Generally speaking what I do with my Steam games that are run via flatpak based source ports (GZDOOM and Yamagi Quake 2) is to place the launch command in the launch options of Steam (yes I know I can simply add as a non Steam game, this feels more elegant to me). In this case, that command is "flatpak run com.github.iortcw.iortcw %command%"

That is not a correct thing to do, for two reasons:

1. The launch command for a Steam game is run with the `LD_LIBRARY_PATH` Steam Runtime, which is not the same as your host system, and can break programs from your host system (including Flatpak)
2. The `%command%` is a complete command-line to be run in that environment, including compatibility tools and Proton, which are irrelevant when running a program from your host system. They will also often refer to paths from your host system which do not exist inside the Flatpak sandbox.

Steam does not have a supported way to run arbitrary commands *instead of* a Steam game. The supported way to run arbitrary commands from within Steam is to add them as a separate non-Steam game shortcut.

If you want to continue to do unsupported things, setting the launch options to something like this:

```
$STEAM_RUNTIME/scripts/switch-runtime-sh --runtime="" -- flatpak run com.github.iortcw.iortcw # instead of %command%
```

should do more or less what you want:

1. `$STEAM_RUNTIME/scripts/switch-runtime-sh --runtime="" --` "escapes" from the `LD_LIBRARY_PATH` Steam Runtime to get back into an environment that is mostly equivalent to what's used for non-Steam game shortcuts;
2. `# instead of %command%` moves the command that Steam originally wanted to run into a shell comment, where it will be ignored, with `flatpak run com.github.iortcw.iortcw` being run instead.

Because this is an unsupported thing to do, future Steam updates might cause this pattern to stop working.

**Comment by HellsBells24** [comment]
That is all good information to have. I believe this post predated my discovery of Luxtorpeda, so what I want is accomplished regardless now. Thank you!

**Comment by Shyshon** [comment]
I just got Luxtorpeda. How would I launch a Flatpak via steam launch options?
