### ISSUE TITLE
Missing LICENSE.md file

### ISSUE THREAD

**Issue by TechnologyClassroom** [iortcw/iortcw#122]
It looks like this is GPL-3.0-or-later.  Adding a LICENSE file to the root directory would make this very obvious for people new to the project.

Would you like me to make a PR to add the GPL?

**Comment by MAN-AT-ARMS** [comment]
The original GPL files are named README.txt within each of the game subdirectories. These are the unmodified originals included with the source release.

**Comment by TechnologyClassroom** [comment]
If we copied the COPYING.txt file to the root directory, it would appear in the `About` heading of the project like it does for the upstream projects.

**Comment by MAN-AT-ARMS** [comment]
Yeah. I'm not opposed to it. Since the single player and multiplayer were released as separate releases I just left as is.
I didn't want to reduce them to just "Return to Castle Wolfenstein" because of Enemy Territory, which isn't a part of this project.
If you want to do that and remove the game designators, I don't think it should be a problem.
