### ISSUE TITLE
ARM64 MacOS Big Sur 

### ISSUE THREAD

**Issue by DoktorCranium** [iortcw/iortcw#128]
Hello,

Git cloned the latest iortcw repo and  patched the make-macosx.sh and make-macosx-ub.sh for (SP and MP) to support ARM64 as well as code/qcommon/q_platform.h  
Also replaced the code/libs/macosx  libSDL2-2.0.0.dylib, libSDL2main.a and libopenal.dylib with my native ARM64 builds from /usr/local 
Everything compiles and the game runs - only thing that does not work is the mouse .. I can access the console in the main window .. issue commands but no mouse ... any ideas where I should look ?  
Im building an running this on Big Sur Apple M1

**Comment by MAN-AT-ARMS** [comment]
Yes, there is something broken with arm64 which is why I haven't added support for it. I see the same issues on M1 Mac Mini. Not sure if it is related to SDL or iortcw itself. ioquake3 I was able to get running but there may be something RTCW specific that is broken in SDL/OpenGL.

**Comment by DoktorCranium** [comment]
Yes - I can confirm the same ioquake  (https://github.com/ec-/Quke3e) builds and runs fine on the M1

**Comment by DoktorCranium** [comment]
BTW I have compiled it and successfully finished the whole game on the AARCH64 Pinebookpro (Manjaro Linux)

**Comment by MAN-AT-ARMS** [comment]
Yes I think it is MacOS specific. SDL team is aware of and confirmed mouse issues on other games as well. I haven't rebuilt from SDL git recently (maybe for a month or so), so I'm not sure of status.

**Comment by tomkidd** [comment]
Yeah this is weird, I can confirm that building the latest SDL code (HEAD of their GitHub repo) still has the issue but only with the ARM64 build of iortcw. Intel build running through Rosetta 2 on an M1 has no issue. 

Do you have any links to where the SDL2 team is discussing this? (i.e., Discourse or GitHub issues)

And yeah it's especially weird since ioq3 isn't experiencing the same issue. Or any other SDL2 games on ARM64 that I've noticed (well, that use the mouse in menus anyway, I guess Quake 1/2 don't)

**Comment by tomkidd** [comment]
OK, after having an epiphany on the drive in to work today I've made some progress.

First, the good news - I don't think SDL2 is the issue because an arm64 build runs and the mouse functions correctly **if you use QVMs**

![image](https://user-images.githubusercontent.com/502580/140243108-323f1a70-fc3c-4b59-bfba-1552da14a2fe.png)

RTCW didn't originally support QVMs (shipped with dlls/dylibs) and iortcw didn't support them properly either until @zturtleman fixed them for me (twice) so I could get the iOS port going a few years back. I'll have to dig up the answer but it was related so memory sharing between the libraries that was advantageous in 2001 and unnecessary on modern hardware. 

So with that in mind as it stands now:

- x86_64 with dylibs (the default): runs and plays game fine
- x86_64 with qvms: runs and plays game fine
- arm64 with dylibs (the default): shows "loading" screen with nonfunctional mouse pointer while you can hear the opening cinematic play and can't do anything about it
- arm64 with qvms: game engine starts as expected, goes to menu, and you can even start a game and see the opening cinematic:

![image](https://user-images.githubusercontent.com/502580/140243996-f29d01fe-e372-4e74-86a2-2db9531ca155.png)

However here's the bad news: trying to start the game (the first level, in the prison) after the cutscene errors out: 

![image](https://user-images.githubusercontent.com/502580/140244390-c9a5772d-e417-4790-b59a-666b1eb8da00.png)

`Hunk_Alloc failed on 4832064`

Anyway that's as far as I've got. Tagging @zturtleman since he's an id Tech 3 wizard and might have an epiphany on what's going wrong.

**Comment by zturtleman** [comment]
RTCW SP and MP did not support QVM. It's one of my pet projects I guess.

As with Quake 3, you can avoid Hunk_Alloc errors by increasing the com_hunkMegs cvar on the command-line at start up (e.g., `iowolfsp +set com_hunkMegs 512`).

I would be interested in the console log of arm64 with dylibs `iowolfsp +set developer 1` to see if it reports UI .menu script load failure or something.

It might be interesting to test if ioquake3 arm64 with dylibs running Quake 3 and Team Arena work. Team Arena in particular because RTCW UI is based on Team Arena UI which is significantly different from Quake 3 UI.

**Comment by tomkidd** [comment]
Interesting, yeah opening it up to 512MB lets it play the actual game. I'll have to look into why, since x86_64 and arm64 needing to allocate the same amount would have been my guess too. 

I'll try the console test this evening and see what it says. Thanks for your help.

**Comment by tomkidd** [comment]
developer mode is sort of a bust, it indicates successful loading of the UI dylib and the only differences between the log when loading from dylib versus qvm are the messages about loading the libraries, timestamps, and the loading times for a few things (which you'd expect to be a little different). Also the bit at the end is different because with the qvms you can actually dismiss the cutscene and go to the menu whereas with the dylibs you can't. 

![image](https://user-images.githubusercontent.com/502580/140616289-1becfd15-3a01-417b-8924-07b96b051df8.png)

![image](https://user-images.githubusercontent.com/502580/140616305-6108a954-fc38-4696-9463-480b467f0aac.png)

I'll probably throw a build on MacSourcePorts that uses qvms until we can sort out the dylib issue. Also still curious why the arm64 version needs more RAM than the x86_64 version

**Comment by MAN-AT-ARMS** [comment]
ioquake3 has the same exact issue with dylibs. Client works but not the game modules (at least not ui). No mouse. qvm's work, but not actual native arm64. It was reported to work on LInux aarch64 but I haven't tested it.

**Comment by fretn** [comment]
I'm having the same issues with rtcwcoop, which makes sense as it is based on iortcw / ioq3.

What I have discovered so far is that the arguments passed with VM_Call are all messed up once they arrive in the vmMain function.

For example I added some debug printing related to the mousemovement and the output looks like this:

`CL_MouseEvent dx: 0 dy: 1` -> this function calls VM_Call with the mouse coords
`VM_Call: 0 1` (see the vm->entryPoint call in the VM_Call function in vm.c, thats where I added this debugprint and only print out the first two arguments which cointain the mouse coords)
`ui.dylib: vmMain: dx: 0, dy:73896` -> this is in the ui library, not only the mouse coords are messed up, but all arguments for all calls to vmMain, that's probably why the game is stuck at loading screen

**Comment by fretn** [comment]
I don't think it's related to ioq3/iortcw 

create the following two files:

main.c:

```
#include <SDL.h>

#define QDECL

void* myHandle = NULL;
intptr_t (QDECL *vmMain)( intptr_t callNum, ... );

int main(int argc, char *argv[]) {
        myHandle = SDL_LoadObject("mylib.dylib");

        vmMain = SDL_LoadFunction(myHandle, "vmMain");

        printf("Calling vmMain(1337, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)\n");
        printf("vmMain returned: %ld\n", vmMain( 1337, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11));
}
```

and mylib.c

```
#include <stdio.h>

#define Q_EXPORT __attribute__((visibility("default")))

Q_EXPORT intptr_t vmMain( intptr_t command, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11  ) {
        printf("vmMain was called with arguments: %ld %ld %ld %ld %ld %ld %ld %ld %ld %ld %ld %ld\n", arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9, arg10, arg11);

        return -1;
}
```

and compile with:

```
gcc -D_THREAD_SAFE -I/opt/homebrew/include/SDL2 -L/opt/homebrew/lib -lSDL2 -o program main.c
gcc mylib.c -c -fPIC
gcc mylib.o -shared -o mylib.dylib
```

When you run the resulting `program`, you get this:

```
[fretn@ceres sample]$ ./program
Calling vmMain(1337, 0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11)
vmMain was called with arguments: 0 73896 5477799995 4366696291 6100202800 10 0 0 1 2 3 4
vmMain returned :-1
[fretn@ceres sample]$
```

As you can see the arguments to `vmMain` arrived messed up in `mylib.dylib`

**Comment by MAN-AT-ARMS** [comment]
Have you tried different compiler flags?

**Comment by fretn** [comment]
no I haven't, any tips on which ones I should use ?

**Comment by fretn** [comment]
solved it:

in `vm_local.h` replace:

`intptr_t (QDECL *entryPoint)( intptr_t callNum, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11);`

with:

`intptr_t (QDECL *entryPoint)( intptr_t callNum, intptr_t arg0, intptr_t arg1, intptr_t arg2, intptr_t arg3, intptr_t arg4, intptr_t arg5, intptr_t arg6, intptr_t arg7, intptr_t arg8, intptr_t arg9, intptr_t arg10, intptr_t arg11);`

**Comment by MAN-AT-ARMS** [comment]
You're right it does work...Weird. Compiler kicks out warning but it does work.

code/qcommon/vm.c:630:46: warning: incompatible pointer types passing 'intptr_t (**)(intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t, intptr_t)' (aka 'long (**)(long, long, long, long, long, long, long, long, long, long, long, long, long)') to parameter of type 'intptr_t (**)(intptr_t, ...)' (aka 'long (**)(long, ...)') [-Wincompatible-pointer-types]
                        vm->dllHandle = Sys_LoadGameDll(filename, &vm->entryPoint, VM_DllSyscall);
                                                                  ^~~~~~~~~~~~~~~
code/qcommon/qcommon.h:1124:67: note: passing argument to parameter 'entryPoint' here
void    * QDECL Sys_LoadGameDll( const char *name, intptr_t (QDECL **entryPoint)(intptr_t, ...),
                                                                     ^
1 warning generated.

**Comment by MAN-AT-ARMS** [comment]
Using Rend2 is broken, at least on M1 Mac Mini.

**Comment by fretn** [comment]
Rend2 works fine in rtcwcoop with above fix applied.

**Comment by MAN-AT-ARMS** [comment]
The game loads but when you go to start a new game it errors out from Com_spintf being too long so the weapon scripts break.

**Comment by fretn** [comment]
works fine too in rtcwcoop, I'm on monterey btw not on big sur

**Comment by MAN-AT-ARMS** [comment]
This is starting a new SP game (iortcw on Big Sur) but the OS version is pretty irrelevant. There's something else going on with the argument sizes. It should work on any version. Which hardware are you running on anyway?

**Comment by fretn** [comment]
https://github.com/rtcwcoop/rtcwcoop/commit/76d43c33df1a548cb839d56f8304fb85df8ad56e

this is what I've done to make it work for rtcwcoop on an M1 Pro, haven't tested this changes yet on iortcw

**Comment by MAN-AT-ARMS** [comment]
Problem commit causing issue when using Rend2 on BigSur (Apple Silicon) was reverted in d4c305d. Seems to be fully working natively on Apple Silicon now.
