### ISSUE TITLE
Fps command doesnt work

### ISSUE THREAD

**Issue by BrazlL** [iortcw/iortcw#157]
The game is stuck at 60 fps.I tried to use /seta com_maxfps 125 but it didnt work.

**Comment by MAN-AT-ARMS** [comment]
You must have vertical sync enabled either in game or in your driver settings.

**Comment by BrazlL** [comment]
It is on and its still not working.

**Comment by MAN-AT-ARMS** [comment]
You don't want those on if you want to adjust frame rate. r_swapinterval 0 and turned off in your driver settings. Otherwise it's going to be locked to your monitor refresh rate.

**Comment by BrazlL** [comment]
I didnt quite understand what you tried to say.I tried to use that command in autoexec, but that made my game 30 fps.

**Comment by MAN-AT-ARMS** [comment]
What I am say is that you do NOT want vertical sync enabled in your graphics driver settings or in game settings (r_swapinterval 0) 
This setting isn't going to be effective when put in the autoexec.cfg file since it is a latched cvar. Edit your wolfconfig.cfg file and make sure it is set to 0. I don't know what type graphics card you have but there is generally also a vertical sync setting in there that you want to disable or let the application decide.

**Comment by BrazlL** [comment]
Ok it is now working.Really thx
