### ISSUE TITLE
Fps caps at 77 on Steam Deck OLED instead of 90fps

### ISSUE THREAD

**Issue by SimonasZab** [iortcw/iortcw#179]
"set com_maxfps 90" works and after that the game always runs at 90fps, but it would be better that the game would detect the correct screen refresh rate.

Tested with linux-x64, win-x64 and win-x86. This occurs in every build

**Comment by MAN-AT-ARMS** [comment]
That isn't better because it affects the physics of the game

**Comment by SimonasZab** [comment]
How does it affect physics? I already played half of the game on 90fps and I did not see any physics anomalies. And if you are saying that higher fps affects physics then why not cap it at 60 fps?

**Comment by MAN-AT-ARMS** [comment]
It's just the way the id Tech3 engine is and all the games that use it. Without an going into too many details, certain frame rates are "better" than others because the engine is time based and many values are rounded up or down. You jump higher and farther, shoot faster, etc. with certain frame rates. You would have to do further reading about it but it's simply not specific to RTCW.
