### ISSUE TITLE
How Can I run iortcw on RaspberryPi... I don't know how to build...

### ISSUE THREAD

**Issue by win3200** [iortcw/iortcw#49]

**Comment by win3200** [comment]
I read the file, README_RASPBERRYPI 

1) Install SDL2-2.0.3.tar.gz
2) sudo apt-get install libudev-dev
3) ./configure --disable-video-x11 --disable-video-opengl
4) ./configure --host=armv7l-raspberry-linux-gnueabihf --disable-video-x11 --disable-video-opengl
5) make
6) sudo make install
7) ./make-raspberry-pi.sh

but...  after launch ./make-raspberry-pi.sh...going...going... It's occured error

**Comment by MAN-AT-ARMS** [comment]
Yeah that script has been broken for a while. It was broken with zturtleman's GL Loader patch in 9e1bb5e.

Raspberry Pi has regular OpenGL support now (not sure if it is still listed as experimental or not) but it is recommended to use OpenGL instead of OpenGLES.

Once you enable the OpenGL driver, you can build SDL with just:
/configure --host=armv7l-raspberry-linux-gnueabihf
make
sudo make install

Then to build iortcw tree just run:
make (instead of using the build script)

I think it should work. I haven't built it for the RPI in a while.

**Comment by zturtleman** [comment]
I fixed compiling the OpenGL ES renderer using `make-raspberrypi.sh` in https://github.com/iortcw/iortcw/commit/3795b5bf5595b30b462885a9c400b78ee14abaa9 (disregard note about running at 3fps, it runs 20-70 after I recompiled it). It needs SDL 2.0.8 [to run on Raspbian stretch](https://hg.libsdl.org/SDL/rev/11462), see updated [README_RASPBERRYPI](https://github.com/iortcw/iortcw/blob/master/README_RASPBERRYPI).

I haven't tested the regular OpenGL driver and iortcw compiled with `make`. Note: need to run `make clean` if switch between compiling using `make` and `./make-raspberrypi.sh`.

**Comment by cesarpuig** [comment]
Hi.

First of all, thank you. I installed it in retropie based on raspbian stretch and it works, but sometimes the image freezes and crashes, and I have to restart. Could you tell me if I can correct it in some way?

**Comment by cesarpuig** [comment]
Hi. sorry, it was the fault of the overclock of my raspberry pi 3b, thanks for your work

**Comment by MAN-AT-ARMS** [comment]
Glad you got it fixed. Have fun.
